changelog:
  categories:
    - title: "Features & Enhancements"
      labels:
        - "feature"
        - "enhancement"
        - "feat"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "Maintenance, Tooling & Refactoring"
      labels:
        - "maintenance"
        - "chore"
        - "ci"
        - "test"
        - "refactor"
